name: Linters
on: [push, pull_request]
env:
    PYLINT_THRESHOLD: ${{ vars.PYLINT_THRESHOLD }}

jobs:
    pylint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: 3.12
            - name: Install dependencies
              run: |
                pip install -U pip
                pip install .[linters]
            - name: Analysing the code with pylint
              run: |
                echo "Pylint success threshold set to ${PYLINT_THRESHOLD:-Undefined, using 8 by default}"
                pylint --fail-under=${PYLINT_THRESHOLD:-8} tokensrv tests

    ruff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/ruff-action@v1
              with:
                changed-files: "true"
